cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('buy-now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove-cart/<int:product_id>/', remove_cart, name='remove_cart'),
    path('checkout/', checkout, name='checkout'), ]

cozastore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    # path('', include('admin_store.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from customer.views import *

app_name = 'customer'
urlpatterns = [
    path('login/', customer_login, name="customer_login"),
    path('logout/', customer_logout, name="customer_logout"),
    path('my-account/', my_account, name='my_account'),
    path('register/', customer_register, name="customer_register"),
    path('user-profile', user_profile, name="user_profile")


]

store/urls.py
from django.urls import path, re_path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', index, name="index"),
    path('product/<int:pk>', product, name="product"),
    path('product-detail/<int:pk>', product_detail, name="product_detail"),
    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('search/<int:pk>', search_product, name="search"),
    path('filter/<int:pk>', filter_product, name="filter"),
    path('product-service/', product_service, name="product_service"),
    # path('blog/', blog, name="blog"),
    # path('blog-detail/', blog_detail, name="blog_detail"),



]

store/models.py
from django.db import models
import datetime
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Status(models.Model):
    status = models.CharField(max_length=250)

    def __str__(self):
        return self.status


class Product(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="dashmain/images",
                              default="dashmain/images/default.png")
    price_sell = models.FloatField()
    price_buy = models.FloatField()
    content = RichTextUploadingField(blank=True, null=True)
    inventory = models.IntegerField()
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    public_day = models.DateTimeField(default=datetime.datetime.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Contact(models.Model):

    email = models.EmailField(max_length=400, null=True)
    message = models.TextField()

    def __str__(self):
        return self.email

store/views.py
from unicodedata import category
from django.shortcuts import render
from idna import alabel
from store.models import Contact, Product, Status, Category
from django.core.paginator import Paginator
from cart.cart import Cart
from store.views import Cart
from rest_framework import viewsets, permissions
from store.serializers import ProductSerializer
from django.http import JsonResponse
from cozastore.settings import EMAIL_HOST_USER
from django.core.mail import send_mail, EmailMultiAlternatives
# Create your views here.


def index(request):
    all_product = Product.objects.all()
    category = Category.objects.all().order_by('name')
    glasses = Product.objects.filter(
        category_id=2).order_by('-public_day')[0:10]
    wallets = Product.objects.filter(
        category_id=4).order_by('-public_day')[0:10]
    bags = Product.objects.filter(category_id=1).order_by('-public_day')[0:10]
    shoes = Product.objects.filter(category_id=3).order_by('-public_day')[0:10]
    jewellery = Product.objects.filter(
        category_id=5).order_by('-public_day')[0:10]
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)
    cart = Cart(request)

    return render(request, "store/index.html", {
        'all_product': product_pager,
        'category': category,
        'glasses': glasses,
        'wallets': wallets,
        'bags': bags,
        'shoes': shoes,
        'jewellery': jewellery,
        'cart': cart

    })


def product(request, pk):
    cart = Cart(request)

    all_product = Product.objects.all()
    if pk == 0:
        # doc het tat ca san pham
        all_product = Product.objects.all()
    else:
        all_product = Product.objects.filter(
            category_id=pk)

    category = Category.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'all_product': product_pager,
        'category': category,
        'cart': cart,

    })


def search_product(request, pk):
    cart = Cart(request)
    all_product = Product.objects.all()
    if pk == 0:
        if request.GET.get('search'):
            search = request.GET.get('search')
            all_product = Product.objects.filter(name__contains=search)
    else:
        if request.GET.get('search'):
            search = request.GET.get('search')
            all_product = Product.objects.filter(
                category_id=pk).filter(name__contains=search)

    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'cart': cart,
        'all_product': product_pager,
        'search': search,

    })


def filter_product(request, pk):
    cart = Cart(request)
    all_product = Product.objects.all()
    if pk == 0:
        # newness
        if request.GET.get('filter_new'):
            all_product = Product.objects.all().order_by('-public_day')
        if request.GET.get('low_to_high'):
            all_product = Product.objects.all().order_by('price_buy')
        if request.GET.get('high_to_low'):
            all_product = Product.objects.all().order_by('-price_buy')

    else:
        if request.GET.get('filter_new'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('-public_day')
        if request.GET.get('low_to_high'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('price_buy')
        if request.GET.get('high_to_low'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('-price_buy')

    category = Category.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'cart': cart,
        'all_product': product_pager,

    })


def product_detail(request, pk):
    cart = Cart(request)

    product = Product.objects.get(id=pk)
    category_id = product.category_id
    category_name = Category.objects.get(id=category_id)
    relate_product = Product.objects.filter(category_id=category_id)

    return render(request, "store/product-detail.html", {
        'product': product,
        'cart': cart,
        'relate_product': relate_product,
        'category_name': category_name
    })


def about(request):
    cart = Cart(request)

    return render(request, "store/about.html", {
        'cart': cart, })


def contact(request):

    cart = Cart(request)

    result_send_mess = ''
    if request.POST.get('btnSend'):
        email = request.POST.get('email')
        message = request.POST.get('message')
        # Khai bao class (model)
        contact = Contact(email=email, message=message)
        contact.save()

        # Thong bao ket qua
        result_send_mess = '''
            <div class="alert alert-success" role="alert">
                You have successfully sent messege!
            </div>
            '''
    # Gui mail
        # message += "\nTest send mail from MyNews website"
        # send_mail(message, email, EMAIL_HOST_USER,
        #           [email, 'tinhntt.98@gmail.com'])

        # message += "<br/><b>Test send mail from MyNews website</b>"
        # msg = EmailMultiAlternatives(message, EMAIL_HOST_USER, [
        #     email, 'tinhntt.98@gmail.com'])
        # msg.attach_alternative(message, 'text/html')
        # msg.send()

    return render(request, "store/contact.html", {
        'cart': cart,
        'result_send_mess': result_send_mess,
    })

# Cach1: Xay dung web service truc tiep


def product_service(request):
    products = Product.objects.all()
    result_list = list(products.values(
        'name', 'price_sell', 'price_buy', 'public_day'))

    return JsonResponse(result_list, safe=False)


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

# def blog(request):
#     cart = Cart(request)

#     return render(request, "store/blog.html", {
#         'cart': cart,
#     })


# def blog_detail(request):
#     cart = Cart(request)

#     return render(request, "store/blog-detail.html", {
#         'cart': cart,
#     })

store/templates/store/checkout.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}
{% block title_tab %}CozaStore | Checkout{% endblock %}

{% block main_content %}
        
    {% comment %} <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:index' %}"> Home</a></li>
                <li class="breadcrumb-item active">Checkout</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End --> {% endcomment %}
    <br>
    <br>

    {% if cart|length > 0 %}
    <div class="row">
        <div class="col-lg-10 col-xl-7 m-lr-auto m-b-20">
            <div class="m-l-25 m-r--38 m-lr-0-xl">
                <div class="wrap-table-shopping-cart">
                    <table class="table-shopping-cart">
                        <tr class="table_head">
                            {% comment %} <th class="column-1">No.</th> {% endcomment %}
                            <th class="column-1" style="text-align: center">Image</th>
                            <th class="column-2" style="text-align: center">Product</th>
                            <th class="column-3" style="text-align: center">Price</th>
                            <th class="column-4" style="text-align: center">Quantity</th>
                            <th class="column-5" style="text-align: center">Total</th>
                        </tr>

                        {%for c in cart%}
                        <tr class="table_row">
                            {% comment %} <td> {{forloop.counter}}</td> {% endcomment %}
                            <td class="column-1" style="text-align: center">
                                <div class="how-itemcart1">
                                    <img src="{{c.product.image.url}}" alt="{{c.product.name}}">
                                </div>
                            </td>
                            <td class="column-2" style="text-align: center">{{c.product.name}}</td>
                            <td class="column-3" style="text-align: center">{{c.price|floatformat:0|intcomma}}</td>
                            <td class="column-4" style="text-align: center">{{c.quantity}}</td>
                            <td class="column-5" style="text-align: center">{{c.total_price|floatformat:0|intcomma}}</td>
                    
                        {%endfor%}
                    </table>
                </div>
                {% comment %} <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
                    <div class="flex-w flex-m m-r-20 m-tb-5">

                            <form method="post" >
                                    {% csrf_token %}
                            <div class="cart-btn">
                                    <button type="submit" id="btnUpdateCart" name="btnUpdateCart" value="UpdateCart" class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10"> Update Cart</button>
                            </div>
                        </form>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>

                <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							Cart Totals
						</h4>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									{{ cart.get_total_price|floatformat:0|intcomma }}
								</span>
							</div>
						</div>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Discount:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									{{ cart.get_discount|floatformat:0|intcomma }}
								</span>
							</div>
						</div>


						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-110 cl2">
									{{ cart.get_final_total_price|floatformat:0|intcomma }}
								</span>
							</div>
						</div>

						<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" type="button" onclick="window.location.href='{% url 'cart:cart_detail'%}';">Update Cart
						</button>
                        <br><br>
                        <form method="post">
                            {% csrf_token %}
                        <button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" onclick="window.location.href='{% url 'cart:checkout'%}';" type="submit" name="btnBuy" value="Buy">Order
						</button>
                        </form>
					</div>
				</div>
			</div>
		</div>
    {% else %}
    <br>
    <br>
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-20">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    You don't have any products in your cart 
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
    {%endif%}

{% endblock %}

store/templates/store/shoping-cart.html
{% extends 'store/_Master.html' %}
{% load static %} 
{% block main_content %}  
{% load humanize %}          
<title> {% block title_tab %} CozaStore | Home {% endblock %} </title>

	<!-- Cart -->
	
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				{% for c in cart %}
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<a href="{% url 'store:product_detail' c.product.id %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
							<img src="{{c.product.image.url}}" alt="{{c.product.name}}">
							</a>
						</div>
						<div class="header-cart-item-txt p-t-8">
							<a href="{% url 'store:product_detail' c.product.id %}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								{{c.product.name}}
							</a>
							<span class="header-cart-item-info">
								{{c.quantity}} x {{c.price|floatformat:0|intcomma}}
							</span>
						</div>
					</li>
				</ul>
				{% endfor %}
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						{{c.total_price|floatformat:0|intcomma}}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{%url 'cart:cart_detail' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="{%url 'cart:checkout' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- breadcrumb -->

	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="{%url 'store:index'%}" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Shoping Cart
			</span>
		</div>
	</div>
	<br>
	<br>
	<br>
	<!-- Shoping Cart -->
		<div class="container">

			{% if not request.session.session_customer %}
			<div class="row mb-5">
				<div class="col-lg-10 col-xl-12 m-lr-auto m-b-50">
					<div class="border p-4 rounded" role="alert">
						Returning customer? <a href="{% url 'customer:customer_login'%}" style="color:#717FE0">Click here</a> to login
					</div>
				</div>
			</div>
			{%endif%}

			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-20">
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						{% if cart|length > 0%}
						<div class="wrap-table-shopping-cart">
							<table class="table-shopping-cart">
								<tr class="table_head">
									<th class="column-1">Image</th>
									<th class="column-2">Product</th>
									<th class="column-3">Price</th>
									<th class="column-4">Quantity</th>
									<th class="column-5">Total</th>
								</tr>

								{%for c in cart%}
								<tr class="table_row">
									<td class="column-1">
										<div class="how-itemcart1" data-toggle="modal" data-target="#sp{{c.product.id}}">
											<img src="{{c.product.image.url}}" alt="{{c.product.name}}">
										</div>
									</td>
									<td class="column-2"><a href="{% url 'store:product_detail' c.product.id %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">{{c.product.name}} </a></td>
									<td class="column-3">{{c.price|floatformat:0|intcomma}}</td>
									<td class="column-4">

										<div class="wrap-num-product flex-w m-l-auto m-r-0">
											<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
												<button class="fs-16 zmdi zmdi-minus" id="btn-minus-{{c.product.id}}"></button>
											</div>

											<input class="mtext-104 cl3 txt-center num-product" type="number" id="quantity1{{c.product.id}}" name="quantity1{{c.product.id}}" value="{{c.quantity}}">

											<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
												<button class="fs-16 zmdi zmdi-plus" id="btn-plus-{{c.product.id}}"></button>
											</div>
										</div>
									</td>
									<td class="column-5">{{c.total_price|floatformat:0|intcomma}}</td>
								</tr>


								<!--Modal-->
									<div class="modal fade" id="sp{{c.product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
										<div class="modal-dialog modal-lg">
											<div class="modal-content">
												<div class="modal-header">
														<h5 class="modal-title" id="sp{{c.product.id}}">Remove Cart</h5>
														<button type="button" class="close" data-dismiss="modal" aria-label="Close">
														<span aria-hidden="true">&times;</span>
														</button>
												</div>
												<div class="modal-body">
														Do you want to remove <b> " {{c.product.name}}" </b> from your shopping cart?
												</div>
												<div class="modal-footer">
														<form method="post" action="{%url 'cart:remove_cart' c.product.pk %}">
																{% csrf_token %}
														<button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
														<button type="submit" class="btn btn-primary">Yes</button>
														</form>
												</div>
											</div>
										</div>
									</div>
							{%endfor%}
							</table>
						</div>

						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
							<form method="post">
								{% csrf_token %}
							<div class="flex-w flex-m m-r-20 m-tb-5">
								<input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" name="coupon_code" value="{{coupon_code}}" placeholder="Coupon Code">
								<button class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10" name="btnCouponCode" value="Use"> Apply Code </button>
							</form>

									<form method="post" >
											{% csrf_token %}
									<div class="cart-btn">
											<button type="submit" id="btnUpdateCart" name="btnUpdateCart" value="UpdateCart" class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10"> Update Cart</button>
									</div>

									{% for c in cart %}
										<input type="hidden" id="quantity2{{c.product.id}}" name="quantity2{{c.product.id}}" value={{c.quantity}}>
										<script>
												$(document).ready(function(){
														$("#quantity1{{c.product.id}}").change(function(){
															let values = $('#quantity1{{c.product.id}}').val();
															$("#quantity2{{c.product.id}}").val(values);
														});
													});
												$(document).ready(function(){
														$("#btn-minus-{{c.product.id}}").click(function(){
																let values = $('#quantity1{{c.product.id}}').val();
																$("#quantity2{{c.product.id}}").val(values);
														});
												});
												$(document).ready(function(){
														$("#btn-plus-{{c.product.id}}").click(function(){
																let values = $('#quantity1{{c.product.id}}').val();
																$("#quantity2{{c.product.id}}").val(values);
														});
												});
						
										</script>
									{% endfor %}
								</form>
							</div>
						</div>
						{%else%}
              <p> No product in your shopping cart <p>
            {%endif%}
					</div>
				</div>
				
				<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							Cart Totals
						</h4>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									{{ cart.get_total_price|floatformat:0|intcomma }}
								</span>
							</div>
						</div>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Discount:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									{{ cart.get_discount|floatformat:0|intcomma }}
								</span>
							</div>
						</div>

						<div class="flex-w flex-t bor12 p-t-15 p-b-30">
							<div class="size-208 w-full-ssm">
								<span class="stext-110 cl2">
									Shipping:
								</span>
							</div>

							<div class="size-209 p-r-18 p-r-0-sm w-full-ssm">
								<p class="stext-111 cl6 p-t-2">
									There are no shipping methods available. Please double check your address, or contact us if you need any help.
								</p>
								
								<div class="p-t-15">
									<span class="stext-112 cl8">
										Calculate Shipping
									</span>

									<div class="bor8 bg0 m-b-12">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="state" placeholder="Address" value="{{ request.session.session_customer.address }}">
									</div>

									<div class="bor8 bg0 m-b-12">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="phone" name="mobile" placeholder="Telephone" value="{{ request.session.session_customer.tel }}">
									</div>

									<div class="bor8 bg0 m-b-12">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="name" placeholder="{{ request.session.session_customer.customer_name }}">
									</div>
									
									<div class="flex-w">
										<div class="flex-c-m stext-101 cl2 size-115 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer">
											Update Totals
										</div>
									</div>

								</div>
							</div>
						</div>

						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-110 cl2">
									{{ cart.get_final_total_price|floatformat:0|intcomma }}
								</span>
							</div>
						</div>

						<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" type="button" onclick="window.location.href='{% url 'cart:checkout'%}';">Proceed to Checkout
						</button>
					</div>
				</div>
			</div>
		</div>

{% endblock %}