cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('buy-now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove-cart/<int:product_id>/', remove_cart, name='remove_cart'),
    path('checkout/', checkout, name='checkout'), ]

cozastore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    # path('', include('admin_store.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, re_path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', index, name="index"),
    path('product/<int:pk>', product, name="product"),
    path('product-detail/<int:pk>', product_detail, name="product_detail"),
    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('search/<int:pk>', search_product, name="search"),
    path('filter/<int:pk>', filter_product, name="filter"),
    path('product-service/', product_service, name="product_service"),
    # path('blog/', blog, name="blog"),
    # path('blog-detail/', blog_detail, name="blog_detail"),



]

store/models.py
from django.db import models
import datetime
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Status(models.Model):
    status = models.CharField(max_length=250)

    def __str__(self):
        return self.status


class Product(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="dashmain/images",
                              default="dashmain/images/default.png")
    price_sell = models.FloatField()
    price_buy = models.FloatField()
    content = RichTextUploadingField(blank=True, null=True)
    inventory = models.IntegerField()
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    public_day = models.DateTimeField(default=datetime.datetime.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Contact(models.Model):

    email = models.EmailField(max_length=400, null=True)
    message = models.TextField()

    def __str__(self):
        return self.email

store/views.py
from unicodedata import category
from django.shortcuts import render
from idna import alabel
from store.models import Contact, Product, Status, Category
from django.core.paginator import Paginator
from cart.cart import Cart
from store.views import Cart
from rest_framework import viewsets, permissions
from store.serializers import ProductSerializer
from django.http import JsonResponse
from cozastore.settings import EMAIL_HOST_USER
from django.core.mail import send_mail, EmailMultiAlternatives
# Create your views here.


def index(request):
    all_product = Product.objects.all()
    category = Category.objects.all().order_by('name')
    glasses = Product.objects.filter(
        category_id=2).order_by('-public_day')[0:10]
    wallets = Product.objects.filter(
        category_id=4).order_by('-public_day')[0:10]
    bags = Product.objects.filter(category_id=1).order_by('-public_day')[0:10]
    shoes = Product.objects.filter(category_id=3).order_by('-public_day')[0:10]
    jewellery = Product.objects.filter(
        category_id=5).order_by('-public_day')[0:10]
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)
    cart = Cart(request)

    return render(request, "store/index.html", {
        'all_product': product_pager,
        'category': category,
        'glasses': glasses,
        'wallets': wallets,
        'bags': bags,
        'shoes': shoes,
        'jewellery': jewellery,
        'cart': cart

    })


def product(request, pk):
    cart = Cart(request)

    all_product = Product.objects.all()
    if pk == 0:
        # doc het tat ca san pham
        all_product = Product.objects.all()
    else:
        all_product = Product.objects.filter(
            category_id=pk)

    category = Category.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'all_product': product_pager,
        'category': category,
        'cart': cart,

    })


def search_product(request, pk):
    cart = Cart(request)
    all_product = Product.objects.all()
    if pk == 0:
        if request.GET.get('search'):
            search = request.GET.get('search')
            all_product = Product.objects.filter(name__contains=search)
    else:
        if request.GET.get('search'):
            search = request.GET.get('search')
            all_product = Product.objects.filter(
                category_id=pk).filter(name__contains=search)

    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'cart': cart,
        'all_product': product_pager,
        'search': search,

    })


def filter_product(request, pk):
    cart = Cart(request)
    all_product = Product.objects.all()
    if pk == 0:
        # newness
        if request.GET.get('filter_new'):
            all_product = Product.objects.all().order_by('-public_day')
        if request.GET.get('low_to_high'):
            all_product = Product.objects.all().order_by('price_buy')
        if request.GET.get('high_to_low'):
            all_product = Product.objects.all().order_by('-price_buy')

    else:
        if request.GET.get('filter_new'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('-public_day')
        if request.GET.get('low_to_high'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('price_buy')
        if request.GET.get('high_to_low'):
            all_product = Product.objects.filter(
                category_id=pk).order_by('-price_buy')

    category = Category.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_product, 20)
    product_pager = paginator.page(page)

    return render(request, "store/product.html", {
        'cart': cart,
        'all_product': product_pager,

    })


def product_detail(request, pk):
    cart = Cart(request)

    product = Product.objects.get(id=pk)
    category_id = product.category_id
    category_name = Category.objects.get(id=category_id)
    relate_product = Product.objects.filter(category_id=category_id)

    return render(request, "store/product-detail.html", {
        'product': product,
        'cart': cart,
        'relate_product': relate_product,
        'category_name': category_name
    })


def about(request):
    cart = Cart(request)

    return render(request, "store/about.html", {
        'cart': cart, })


def contact(request):

    cart = Cart(request)

    result_send_mess = ''
    if request.POST.get('btnSend'):
        email = request.POST.get('email')
        message = request.POST.get('message')
        # Khai bao class (model)
        contact = Contact(email=email, message=message)
        contact.save()

        # Thong bao ket qua
        result_send_mess = '''
            <div class="alert alert-success" role="alert">
                You have successfully sent messege!
            </div>
            '''
    # Gui mail
        # message += "\nTest send mail from MyNews website"
        # send_mail(message, email, EMAIL_HOST_USER,
        #           [email, 'tinhntt.98@gmail.com'])

        # message += "<br/><b>Test send mail from MyNews website</b>"
        # msg = EmailMultiAlternatives(message, EMAIL_HOST_USER, [
        #     email, 'tinhntt.98@gmail.com'])
        # msg.attach_alternative(message, 'text/html')
        # msg.send()

    return render(request, "store/contact.html", {
        'cart': cart,
        'result_send_mess': result_send_mess,
    })

# Cach1: Xay dung web service truc tiep


def product_service(request):
    products = Product.objects.all()
    result_list = list(products.values(
        'name', 'price_sell', 'price_buy', 'public_day'))

    return JsonResponse(result_list, safe=False)


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

# def blog(request):
#     cart = Cart(request)

#     return render(request, "store/blog.html", {
#         'cart': cart,
#     })


# def blog_detail(request):
#     cart = Cart(request)

#     return render(request, "store/blog-detail.html", {
#         'cart': cart,
#     })

store/templates/store/parts/all_product.html
{% load static %}
{% load humanize %}

	<!-- Block2 -->
  <div class="row isotope-grid">
    {%for product in glasses %}
    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women">
      <!-- Block2 -->
      <div class="block2">
        <div class="block2-pic hov-img0">
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            <img src="{{product.image.url}}" alt="{{product.name}}">
          </a>

          {% comment %} <button class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
            Add to cart
          </button> {% endcomment %}
        </div>

        <div class="block2-txt flex-w flex-t p-t-14">
          <div class="block2-txt-child1 flex-col-l ">
            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
              {{product.name}}
            </a>

            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            <span class="stext-105 cl3">
              {{product.price_sell |floatformat:0|intcomma}}vnd
            </span>
            </a>
            <span class="stext-105 cl3">
              {{product.status}}
            </span>
          </div>

          <div class="block2-txt-child2 flex-r p-t-3">
            <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
              <img class="icon-heart1 dis-block trans-04" src="{% static 'store/images/icons/icon-heart-01.png' %}" alt="ICON">
              <img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'store/images/icons/icon-heart-02.png' %}" alt="ICON">
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

    <!-- Wallets -->
    
    {% for product in wallets %}
    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item men">
      <!-- Block2 -->
      <div class="block2">
        <div class="block2-pic hov-img0">
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            <img src="{{product.image.url}}" alt="{{product.name}}">
          </a>

          <a href="#" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
            Quick View
          </a>
        </div>

        <div class="block2-txt flex-w flex-t p-t-14">
          <div class="block2-txt-child1 flex-col-l ">
            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
              {{product.name}}
            </a>

            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            <span class="stext-105 cl3">
              {{product.price_sell |floatformat:0|intcomma}}vnd
            </span>
            </a>
            <span class="stext-105 cl3">
              {{product.status}}
            </span>
          </div>

          <div class="block2-txt-child2 flex-r p-t-3">
            <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
              <img class="icon-heart1 dis-block trans-04" src="{% static 'store/images/icons/icon-heart-01.png' %}" alt="ICON">
              <img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'store/images/icons/icon-heart-02.png' %}" alt="ICON">
            </a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% for product in bags %}
  <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item bag">
    <!-- Block2 -->
    <div class="block2">
      <div class="block2-pic hov-img0">
        <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
        <img src="{{product.image.url}}" alt="{{product.name}}">
        </a>

        <a href="#" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
          Quick View
        </a>
      </div>

      <div class="block2-txt flex-w flex-t p-t-14">
        <div class="block2-txt-child1 flex-col-l ">
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            {{product.name}}
          </a>

          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
          <span class="stext-105 cl3">
            {{product.price_sell |floatformat:0|intcomma}}vnd
          </span>
          </a>
          <span class="stext-105 cl3">
            {{product.status}}
          </span>
        </div>

        <div class="block2-txt-child2 flex-r p-t-3">
          <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
            <img class="icon-heart1 dis-block trans-04" src="{% static 'store/images/icons/icon-heart-01.png' %}" alt="ICON">
            <img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'store/images/icons/icon-heart-02.png' %}" alt="ICON">
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
    
  {% for product in jewellery %}
  <!--Jewellery-->
    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item watches">
      <!-- Block2 -->
    <div class="block2">
      <div class="block2-pic hov-img0">
        <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
        <img src="{{product.image.url}}" alt="{{product.name}}">
        </a>

        <a href="#" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
          Quick View
        </a>
      </div>

      <div class="block2-txt flex-w flex-t p-t-14">
        <div class="block2-txt-child1 flex-col-l ">
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            {{product.name}}
          </a>
          
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
          <span class="stext-105 cl3">
            {{product.price_sell |floatformat:0|intcomma}}vnd
          </span>
          </a>
          <span class="stext-105 cl3">
            {{product.status}}
          </span>
        </div>

        <div class="block2-txt-child2 flex-r p-t-3">
          <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
            <img class="icon-heart1 dis-block trans-04" src="{% static 'store/images/icons/icon-heart-01.png' %}" alt="ICON">
            <img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'store/images/icons/icon-heart-02.png' %}" alt="ICON">
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  
  {% for product in shoes %}
    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item shoes">
      <!-- Block2 -->
      <div class="block2">
        <div class="block2-pic hov-img0">
          <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
          <img src="{{product.image.url}}" alt="{{product.name}}">
          </a>

          <a href="#" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
            Quick View
          </a>
        </div>

        <div class="block2-txt flex-w flex-t p-t-14">
          <div class="block2-txt-child1 flex-col-l ">
            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
              {{product.name}}
            </a>

            <a href="{% url 'store:product_detail' product.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
            <span class="stext-105 cl3">
              {{product.price_sell |floatformat:0|intcomma}}vnd
            </span>
            </a>
            <span class="stext-105 cl3">
              {{product.status}}
            </span>
          </div>

          <div class="block2-txt-child2 flex-r p-t-3">
            <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
              <img class="icon-heart1 dis-block trans-04" src="{% static 'store/images/icons/icon-heart-01.png' %}" alt="ICON">
              <img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'store/images/icons/icon-heart-02.png' %}" alt="ICON">
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- Load more -->
  <div class="flex-c-m flex-w w-full p-t-45">
    <a href="#" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
      Load More
    </a>
  </div>
</div>
</div>

store/templates/store/parts/cart_bar.html
{% load static%}
{% load humanize%}
  <!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				{% for c in cart %}
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<a href="{% url 'store:product_detail' c.product.id %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
							<img src="{{c.product.image.url}}" alt="{{c.product.name}}">
							</a>
						</div>
						<div class="header-cart-item-txt p-t-8">
							<a href="{% url 'store:product_detail' c.product.id %}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								{{c.product.name}}
							</a>
							<span class="header-cart-item-info">
								{{c.quantity}} x {{c.price|floatformat:0|intcomma}}
							</span>
						</div>
					</li>
				</ul>
				{% endfor %}
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						{{c.total_price|floatformat:0|intcomma}}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{%url 'cart:cart_detail' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="{%url 'cart:checkout' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>

store/templates/store/parts/script.html
 {% load static %}
 
 <!-- Vendor JS Files -->
 <script src="{% static 'store/assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/chart.js/chart.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/echarts/echarts.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/quill/quill.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
 <script src="{% static 'store/assets/vendor/tinymce/tinymce.min.js' %}"></script>
 <script src="{% static 'store/assets/vendor/php-email-form/validate.js' %}"></script>

 <!-- Template Main JS File -->
 <script src="{% static 'store/assets/js/main.js' %}"></script>

store/templates/store/parts/slide_bar.html
{% load static%}

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

  <ul class="sidebar-nav" id="sidebar-nav">

    <li class="nav-item">
      <a class="nav-link " href="{% url 'store:index' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li><!-- End Dashboard Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-menu-button-wide"></i><span>Product</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'store:product' %}">
            <i class="bi bi-circle"></i><span>Tables Product</span>
          </a>
        </li>
        <li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-journal-text"></i><span>Invoices</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="forms-elements.html">
            <i class="bi bi-circle"></i><span>Form Elements</span>
          </a>
        </li>
        <li>
          <a href="forms-layouts.html">
            <i class="bi bi-circle"></i><span>Form Layouts</span>
          </a>
        </li>
        <li>
          <a href="forms-editors.html">
            <i class="bi bi-circle"></i><span>Form Editors</span>
          </a>
        </li>
        <li>
          <a href="forms-validation.html">
            <i class="bi bi-circle"></i><span>Form Validation</span>
          </a>
        </li>
      </ul>
    </li><!-- End Forms Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-layout-text-window-reverse"></i><span>Customer</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="tables-general.html">
            <i class="bi bi-circle"></i><span>General Tables</span>
          </a>
        </li>
        <li>
          <a href="tables-data.html">
            <i class="bi bi-circle"></i><span>Data Tables</span>
          </a>
        </li>
      </ul>
    </li><!-- End Tables Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-bar-chart"></i><span>Reports</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="charts-chartjs.html">
            <i class="bi bi-circle"></i><span>Chart.js</span>
          </a>
        </li>
        <li>
          <a href="charts-apexcharts.html">
            <i class="bi bi-circle"></i><span>ApexCharts</span>
          </a>
        </li>
        <li>
          <a href="charts-echarts.html">
            <i class="bi bi-circle"></i><span>ECharts</span>
          </a>
        </li>
      </ul>
    </li><!-- End Charts Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-gem"></i><span>Employee</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="icons-bootstrap.html">
            <i class="bi bi-circle"></i><span>Bootstrap Icons</span>
          </a>
        </li>
        <li>
          <a href="icons-remix.html">
            <i class="bi bi-circle"></i><span>Remix Icons</span>
          </a>
        </li>
        <li>
          <a href="icons-boxicons.html">
            <i class="bi bi-circle"></i><span>Boxicons</span>
          </a>
        </li>
      </ul>
    </li><!-- End Icons Nav -->

    <li class="nav-heading">Pages</li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="users-profile.html">
        <i class="bi bi-person"></i>
        <span>Selling</span>
      </a>
    </li><!-- End Profile Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-faq.html">
        <i class="bi bi-question-circle"></i>
        <span>Profile</span>
      </a>
    </li><!-- End F.A.Q Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-contact.html">
        <i class="bi bi-envelope"></i>
        <span>Contact</span>
      </a>
    </li><!-- End Contact Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-register.html">
        <i class="bi bi-card-list"></i>
        <span>Register</span>
      </a>
    </li><!-- End Register Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-login.html">
        <i class="bi bi-box-arrow-in-right"></i>
        <span>Login</span>
      </a>
    </li><!-- End Login Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-error-404.html">
        <i class="bi bi-dash-circle"></i>
        <span>Error 404</span>
      </a>
    </li><!-- End Error 404 Page Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-blank.html">
        <i class="bi bi-file-earmark"></i>
        <span>Blank</span>
      </a>
    </li><!-- End Blank Page Nav -->

  </ul>

</aside><!-- End Sidebar-->